/* ============================================================
   مشغل القرآن الكريم - سوفتارا (سكربت خارجي مستقل)
   ============================================================
   هذا الملف يصلح كسرين حدثا داخل قالب المنتدى عندما حذفت
   المنصة الأقواس الفارغة {} من السكربت المدمج:
     1) catch (e) { } في دالة fillLists
     2) function () { } داخل audio.play().catch(...)
   النتيجة كانت: Unexpected identifier 'filled' + Unexpected end
   of input، وموت مشغل القرآن بالكامل.
   يُحمَّل عبر سطر واحد في القالب بدل السكربت المدمج، فلا تتأثر
   به عملية حفظ القوالب مستقبلاً.
   ============================================================ */
(function () {var RECITERS = [["مشاري راشد العفاسي", "https://server8.mp3quran.net/afs/"],["ماهر المعيقلي", "https://server12.mp3quran.net/maher/"],["عبدالباسط عبدالصمد", "https://server7.mp3quran.net/basit/"],["محمود خليل الحصري", "https://server13.mp3quran.net/husr/"],["عبدالرحمن السديس", "https://server11.mp3quran.net/sds/"],["ياسر الدوسري", "https://server11.mp3quran.net/yasser/"],["أحمد بن علي العجمي", "https://server10.mp3quran.net/ajm/"],["ناصر القطامي", "https://server6.mp3quran.net/qtm/"],["أبو بكر الشاطري", "https://server11.mp3quran.net/shatri/"],["إبراهيم الأخضر", "https://server6.mp3quran.net/akdr/"]];var SURAHS = ["الفاتحة","البقرة","آل عمران","النساء","المائدة","الأنعام","الأعراف","الأنفال","التوبة","يونس","هود","يوسف","الرعد","إبراهيم","الحجر","النحل","الإسراء","الكهف","مريم","طه","الأنبياء","الحج","المؤمنون","النور","الفرقان","الشعراء","النمل","القصص","العنكبوت","الروم","لقمان","السجدة","الأحزاب","سبأ","فاطر","يس","الصافات","ص","الزمر","غافر","فصلت","الشورى","الزخرف","الدّخان","الجاثية","الأحقاف","محمد","الفتح","الحجرات","ق","الذاريات","الطور","النجم","القمر","الرحمن","الواقعة","الحديد","المجادلة","الحشر","الممتحنة","الصف","الجمعة","المنافقون","التغابن","الطلاق","التحريم","الملك","القلم","الحاقة","المعارج","نوح","الجن","المزمل","المدثر","القيامة","الإنسان","المرسلات","النبأ","النازعات","عبس","التكوير","الإنفطار","المطففين","الإنشقاق","البروج","الطارق","الأعلى","الغاشية","الفجر","البلد","الشمس","الليل","الضحى","الشرح","التين","العلق","القدر","البينة","الزلزلة","العاديات","القارعة","التكاثر","العصر","الهمزة","الفيل","قريش","الماعون","الكوثر","الكافرون","النصر","المسد","الإخلاص","الفلق","الناس"];var filled = false;
function fillLists() {if (filled) { return; }var rSel = document.getElementById('quranReciter');var sSel = document.getElementById('quranSurah');if (!rSel || !sSel) { return; }var i, opt;for (i = 0; i < RECITERS.length; i++) {opt = document.createElement('option');opt.value = i; opt.textContent = RECITERS[i][0];rSel.appendChild(opt);}for (i = 0; i < SURAHS.length; i++) {opt = document.createElement('option');opt.value = i + 1; opt.textContent = (i + 1) + '. سورة ' + SURAHS[i];sSel.appendChild(opt);}try {var lr = parseInt(localStorage.getItem('quran_reciter'), 10);var ls = parseInt(localStorage.getItem('quran_surah'), 10);if (!isNaN(lr) && lr >= 0 && lr < RECITERS.length) { rSel.value = lr; }if (!isNaN(ls) && ls >= 1 && ls <= 114) { sSel.value = ls; }} catch (e) { }
    filled = true;
}

function pad3(n) { n = String(n); while (n.length < 3) { n = '0' + n; } return n; }

function loadCurrent(autoplay) {var rSel = document.getElementById('quranReciter');var sSel = document.getElementById('quranSurah');var audio = document.getElementById('quranAudio');var now = document.getElementById('quranNowPlaying');if (!rSel || !sSel || !audio) { return; }var r = parseInt(rSel.value, 10) || 0;var s = parseInt(sSel.value, 10) || 1;audio.src = RECITERS[r][1] + pad3(s) + '.mp3';if (now) { now.textContent = 'سورة ' + SURAHS[s - 1] + ' — ' + RECITERS[r][0]; }try {localStorage.setItem('quran_reciter', r);localStorage.setItem('quran_surah', s);} catch (e) { }
    if (autoplay) { audio.play().catch(function () { }); }}window.quranSelectionChanged = function () { loadCurrent(true); };
window.quranStep = function (dir) {var sSel = document.getElementById('quranSurah');if (!sSel) { return; }var s = parseInt(sSel.value, 10) || 1;s += dir;if (s < 1) { s = 114; }if (s > 114) { s = 1; }sSel.value = s;loadCurrent(true);};
window.openQuranPlayer = function () {fillLists();var m = document.getElementById('quranModal');if (m) { m.classList.add('active'); }var audio = document.getElementById('quranAudio');if (audio && !audio.getAttribute('src')) { loadCurrent(false); }/* تحديث العرض بعد فتح النافذة مباشرة لضمان ظهور القارئ والسورة */setTimeout(function () { var rSel = document.getElementById('quranReciter'); var sSel = document.getElementById('quranSurah'); var now = document.getElementById('quranNowPlaying'); if (rSel && sSel && now) { var r = parseInt(rSel.value, 10) || 0; var s = parseInt(sSel.value, 10) || 1; now.textContent = 'سورة ' + SURAHS[s - 1] + ' — ' + RECITERS[r][0]; } }, 50);};
window.closeQuranPlayer = function () {var m = document.getElementById('quranModal');if (m) { m.classList.remove('active'); }};
document.addEventListener('DOMContentLoaded', function () {var audio = document.getElementById('quranAudio');if (audio) { audio.addEventListener('ended', function () { window.quranStep(1); }); }var m = document.getElementById('quranModal');if (m) { m.addEventListener('click', function (e) { if (e.target === this) { window.closeQuranPlayer(); } }); }});})();
