name: Release Automation

on:
  workflow_dispatch:

  release:
    types:
      - published

permissions:
  contents: write

jobs:
  release-info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Python Script
        run: |
          python scripts/upload_to_vt.py
